app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
use App\Vessel;
use App\VesselTypes;
use Illuminate\Support\Facades\Storage;

Route::group(['web'], function(){

    Route::get('/t', function () {
        $src = Vessel::find(8);
        echo "<img src='$src->image_url'/>";
    });

    Route::get('/', function () {
//        return '<h1 style="text-align: center;margin-top:200px;font-family:Calibri;">Site is down for maintenance</h1>';
        return view('home');
    });

    Route::get('/fleet/{id}', function($id){
        $types = VesselTypes::get();
        $vessels = Vessel::where('vessel_type_id', $id)->get();
        return view('vessel-type', compact('vessels', 'types'));
    });

    Route::get('/about', function () {
        return view('about');
    });
    Route::get('/companies', function () {
        return view('companies');
    });
    Route::get('/certifications', function () {
        return view('certifications');
    });
    Route::get('/pols', function () {
        return view('policiess');
    });
    Route::get('/certifications', function () {
        return view('certifications');
    });
    Route::get('/clients', function () {
        return view('clients');
    });
    Route::get('/company-history', function () {
        return view('company-history');
    });
    Route::get('/locations', function () {
        return view('locations');
    });
    Route::get('/career', function () {
        return view('career');
    });
    Route::get('/services', function () {
        return view('services');
    });

    Route::get('/testimonials', function () {
        return view('testimonials');
    });

    Route::get('/services/pipe', function () {
        return view('/services/pipe');
    });

    Route::get('/services/positioning', function () {
        return view('/services/positioning');
    });

    Route::get('/services/cdi', function () {
        return view('/services/cdi');
    });
    Route::get('/services/chandler', function () {
        return view('/services/chandler');
    });
    Route::get('/services/tankers', function () {
        return view('/services/tankers');
    });
    Route::get('/services/offshore', function () {
        return view('/services/offshore');
    });
    Route::get('/services/diving', function () {
        return view('/services/diving');
    });
    Route::get('/services/rov', function () {
        return view('/services/rov');
    });
    Route::get('/services/inspections', function () {
        return view('/services/inspections');
    });
    Route::get('/services/brokering', function () {
        return view('/services/brokering');
    });
    Route::get('/services/catering', function () {
        return view('/services/catering');
    });
    Route::get('/services/supplychain', function () {
        return view('/services/supplychain');
    });
    Route::get('/services/erp', function () {
        return view('/services/erp');
    });

    Route::post('/contactpost', function(\Illuminate\Http\Request $request){
        $name = $request->name;
        $email = $request->email;
        $subject = $request->subject;
        $note = $request->message;
        Mail::send('contactemail', ['name' => $name, 'email' => $email, 'subject' => $subject, 'note' => $note], function ($m) use ($subject, $email) {
            $m->subject($subject);
            $m->from($email);
            $m->to('canops@canega.com');
        });

        return Redirect::back()->withInput()->with('success', 'Your message was successfully delivered.');
    });

    Route::get('/fleet', function(){
        $mpsv =  Vessel::where('vessel_type_id', 1)->get();
        $psv =  Vessel::where('vessel_type_id', 2)->get();
        $fisv =  Vessel::where('vessel_type_id', 3)->get();
        $spm =  Vessel::where('vessel_type_id', 4)->get();
        return view('fleet', compact('mpsv', 'psv', 'fisv', 'spm'));
    });
    
    Route::get('/contact', function () {
        return view('contact');
    });


    Route::auth();

    Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){
        Route::get('/', function(){
            return redirect('/admin/vessels');
        });

        Route::resource('vessel-types', 'TypesController');
        Route::resource('vessels', 'VesselController');
    });

});



Route::get('sendtest', function(){

    ini_set( 'display_errors', 1 );
    error_reporting( E_ALL );
    $from = "noreply@menparkenterprises.com";
    $to = "srosenthal82@gmail.com";
    $subject = "PHP Mail Test script";
    $message = "This is a test to check the PHP Mail functionality";
    $headers = "From:" . $from;
    dd(mail($to,$subject,$message, $headers));
    echo "Test email sent";
});

app/Vessel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vessel extends Model
{
    protected $fillable = [
        'name',
        'built',
        'class',
        'crane',
        'mooring',
        'beds',
        'firefighting',
        'loa',
        'speed',
        'clear_deck_area',
        'deck_cargo_load',
        'fresh_water',
        'liquid_mud',
        'fuel_oil',
        'drill_water'
    ];
    public function vessel_type()
    {
        return $this->belongsTo(VesselTypes::class);
    }
}

app/VesselTypes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VesselTypes extends Model
{
    protected $table = 'vessel_types';

    protected $fillable = ['name', 'abbreviation'];

    public function vessels()
    {
        return $this->hasMany(Vessel::class);
    }
}

app/Http/Controllers/VesselController.php
<?php

namespace App\Http\Controllers;

use App\Vessel;
use App\VesselTypes;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Storage;

class VesselController extends Controller
{
    public function index()
    {
        $vessels = Vessel::with('vessel_type')->get();
        return view('admin.home', compact('vessels'));
    }

    public function create()
    {
        $types = VesselTypes::lists('name', 'id');
        return view('admin.vessels.create', compact('types'));
    }

    public function store(Request $request)
    {
        $disk = Storage::disk('s3');
        $input = $request->all();
        $type = VesselTypes::find($input['type']);
        $vessel = new Vessel();
        $vessel->fill($input);
        $vessel->vessel_type()->associate($type);

        if ($request->hasFile('my_pdf')) {
            $pdf = $request->file('my_pdf');
            $original_name = $pdf->getClientOriginalName();
            $name = $vessel->name . "-" . $original_name;
            $path = 'vessels/pdfs/'. $name;
            $disk->put($path, file_get_contents($request->file('my_pdf'), 'public'));
            $vessel->pdf_url =  $this->getFilePathAttribute($path);
        }
        if ($request->hasFile('my_image')) {
            $image = $request->file('my_image');
            $original_name = $image->getClientOriginalName();
            $name = $vessel->name . "-" . $original_name;
            $path = 'vessels/images/'. $name;
            $disk->put($path, file_get_contents($request->file('my_image'), 'public'));
            $vessel->image_url =  $this->getFilePathAttribute($path);
        }
        $vessel->save();
        return redirect('admin/vessels');
    }

    public function edit($id)
    {
        $vessel = Vessel::with('vessel_type')->find($id);
        $types = VesselTypes::lists('name', 'id');
        return view('admin/vessels/edit', compact('vessel', 'types'));
    }

    public function update($id, Request $request)
    {
        $disk = Storage::disk('s3');
        $input = $request->all();
        $type = VesselTypes::find($input['type']);
        $vessel = Vessel::with('vessel_type')->find($id);
        $vessel->update($input);
        $vessel->vessel_type()->associate($type);

        if ($request->hasFile('my_pdf')) {
            $pdf = $request->file('my_pdf');
            $original_name = $pdf->getClientOriginalName();
            $name = $vessel->name . "-" . $original_name;
            $path = 'vessels/pdfs/'. $name;
            $disk->put($path, file_get_contents($request->file('my_pdf'), 'public'));
            $vessel->pdf_url =  $this->getFilePathAttribute($path);
        }
        if ($request->hasFile('my_image')) {
            $image = $request->file('my_image');
            $original_name = $image->getClientOriginalName();
            $name = $vessel->name . "-" . $original_name;
            $path = 'vessels/images/'. $name;
            $disk->put($path, file_get_contents($request->file('my_image'), 'public'));
            $vessel->image_url =  $this->getFilePathAttribute($path);
        }
        $vessel->save();
        return redirect('admin/vessels');
    }

    public function destroy($id)
    {
        Vessel::destroy($id);
        return redirect()->back();
    }


    public function getFilePathAttribute($value)
    {
        $disk = Storage::disk('s3');
        $bucket = Config::get('filesystems.disks.s3.bucket');
        if ($disk->exists($value)) {
            $request = $disk->getDriver()->getAdapter()->getClient()->getObjectUrl($bucket, $value);
            return (string) $request;
        }
        return $value;
    }
}

resources/views/admin/vessels/create.blade.php
@extends('layout')

@section('content')

    <div class="container" >
        <h2>Add a New Vessel</h2>
        <div ng-controller="createController">
            <form action="{{route('admin.vessels.store')}}" method="post" enctype="multipart/form-data" >
                {{csrf_field()}}
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Type</label>
                            {!! Form::select('type', $types, null, ['class' => 'form-control', 'ng-model' => 'type']) !!}
                        </div>
                        <div class="form-group">
                            <label >Vessel Name</label>
                            <input type="text" class="form-control" name="name" />
                        </div>
                        <div class="form-group">
                            <label>Built</label>
                            <input type="text" class="form-control" name="built"/>
                        </div>
                        <div class="form-group">
                            <label>Class</label>
                            <input type="text" class="form-control" name="class"/>
                        </div>

                    </div>
                    <div class="col-md-6">
                        <div class="form-group" ng-if="type==1 || type==2">
                            <label>Crane</label>
                            <input type="text" class="form-control" name="crane"/>
                        </div>
                        <div class="form-group" ng-if="type==1 || type==2">
                            <label>4 PT Mooring</label>
                            {!! Form::select('mooring', ['Yes' => 'Yes', 'No' => 'No'], null, ['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group" ng-if="type==1 || type==2">
                            <label>Beds</label>
                            <input type="text" class="form-control" name="beds"/>
                        </div>
                        <div class="form-group" ng-if="type!=1">
                            <label>LOA</label>
                            <input type="text" class="form-control" name="loa"/>
                        </div>
                        <div class="form-group" ng-if="type==3 || type==4">
                            <label>Speed</label>
                            <input type="text" class="form-control" name="speed"/>
                        </div>
                        <div class="form-group" ng-if="type==3 || type==4">
                            <label>Pax</label>
                            <input type="text" class="form-control" name="pax"/>
                        </div>
                        <div class="form-group" ng-if="type==3">
                            <label>Clear Deck Space</label>
                            <input type="text" class="form-control" name="clear_deck_space"/>
                        </div>
                        <div class="form-group" ng-if="type==3">
                            <label>Deck Cargo Capacity</label>
                            <input type="text" class="form-control" name="deck_cargo_capacity"/>
                        </div>

                        <div class="form-group">
                            <label>Fire Fighting</label>
                            <input type="text" class="form-control" name="firefighting"/>
                        </div>

                    </div>
                </div>
                <div class="row" ng-if="type==2">
                    <div class="col-md-12">
                        <h3>PSV Specific</h3>
                        <div class="form-group">
                            <label>Clear Deck Area</label>
                            <input type="text" class="form-control" name="clear_deck_area"/>
                        </div>
                        <div class="form-group">
                            <label>Deck Cargo Load</label>
                            <input type="text" class="form-control" name="deck_cargo_load"/>
                        </div>
                        <div class="form-group">
                            <label>Potable/Fresh Water</label>
                            <input type="text" class="form-control" name="fresh_water"/>
                        </div>
                        <div class="form-group">
                            <label>Liquid Mud</label>
                            <input type="text" class="form-control" name="liquid_mud"/>
                        </div>
                        <div class="form-group">
                            <label>Fuel  Oil</label>
                            <input type="text" class="form-control" name="fuel_oil"/>
                        </div>
                        <div class="form-group">
                            <label>Drill Water</label>
                            <input type="text" class="form-control" name="drill_water"/>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Upload PDF</label>
                            <input type="file" name="my_pdf">
                        </div>
                        <div class="form-group">
                            <label>Upload Image</label>
                            <input type="file" name="my_image">
                        </div>
                    </div>
                </div>

                <button type="submit" class="btn btn-lg btn-primary pull-right">Submit</button>
                <div class="clearfix"></div>
                <br>
            </form>
        </div>

    </div>
@endsection

@section('footer')
    <script src="/js/angular.js"></script>
    <script>
        var myApp = angular.module('myApp', [], function($interpolateProvider) {
            $interpolateProvider.startSymbol('<%');
            $interpolateProvider.endSymbol('%>');
        });

        myApp.controller('createController', ['$scope', function($scope){

        }]);

    </script>
@endsection

resources/views/admin/vessels/edit.blade.php
@extends('layout')

@section('content')

    <div class="container" ng-controller="editController">
        <h2>Edit {{$vessel->name}}</h2>
        <form action="{{route('admin.vessels.update', ['id' => $vessel->id])}}" method="post" enctype="multipart/form-data">
            {{csrf_field()}}
            <input name="_method" type="hidden" value="PUT">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Type</label>
                        {!! Form::select('type', $types, null, ['class' => 'form-control', 'ng-model' => 'type']) !!}
                    </div>
                    <div class="form-group">
                        <label >Vessel Name</label>
                        <input type="text" class="form-control" name="name" value="{{$vessel->name}}"/>
                    </div>
                    <div class="form-group">
                        <label>Built</label>
                        <input type="text" class="form-control" name="built" value="{{$vessel->built}}"/>
                    </div>
                    <div class="form-group">
                        <label>Class</label>
                        <input type="text" class="form-control" name="class" value="{{$vessel->class}}"/>
                    </div>

                </div>
                <div class="col-md-6">
                    <div class="form-group" ng-if="type==1 || type==2">
                        <label>Crane</label>
                        <input type="text" class="form-control" name="crane"/>
                    </div>
                    <div class="form-group" ng-if="type==1 || type==2">
                        <label>4 PT Mooring</label>
                        {!! Form::select('mooring', ['Yes' => 'Yes', 'No' => 'No'], null, ['class' => 'form-control']) !!}
                    </div>
                    <div class="form-group" ng-if="type==1 || type==2">
                        <label>Beds</label>
                        <input type="text" class="form-control" name="beds" value="{{$vessel->beds}}"/>
                    </div>
                    <div class="form-group" ng-if="type!=1">
                        <label>LOA</label>
                        <input type="text" class="form-control" name="loa" value="{{$vessel->loa}}"/>
                    </div>
                    <div class="form-group" ng-if="type==3 || type==4">
                        <label>Speed</label>
                        <input type="text" class="form-control" name="speed" value="{{$vessel->speed}}"/>
                    </div>
                    <div class="form-group" ng-if="type==3 || type==4">
                        <label>Pax</label>
                        <input type="text" class="form-control" name="pax" value="{{$vessel->pax}}"/>
                    </div>

                    <div class="form-group">
                        <label>Fire Fighting</label>
                        <input type="text" class="form-control" name="firefighting" value="{{$vessel->firefighting}}"/>
                    </div>

                </div>
            </div>



            <div class="row" ng-if="type==2">
                <div class="col-md-12">
                    <h3>PSV Specific</h3>
                    <div class="form-group">
                        <label>Clear Deck Area</label>
                        <input type="text" class="form-control" name="clear_deck_area" value="{{$vessel->clear_deck_area}}"/>
                    </div>
                    <div class="form-group">
                        <label>Deck Cargo Load</label>
                        <input type="text" class="form-control" name="deck_cargo_load" value="{{$vessel->deck_cargo_load}}"/>
                    </div>
                    <div class="form-group">
                        <label>Potable/Fresh Water</label>
                        <input type="text" class="form-control" name="fresh_water" value="{{$vessel->fresh_water}}"/>
                    </div>
                    <div class="form-group">
                        <label>Liquid Mud</label>
                        <input type="text" class="form-control" name="liquid_mud" value="{{$vessel->liquid_mud}}"/>
                    </div>
                    <div class="form-group">
                        <label>Fuel  Oil</label>
                        <input type="text" class="form-control" name="fuel_oil" value="{{$vessel->fuel_oil}}"/>
                    </div>
                    <div class="form-group">
                        <label>Drill Water</label>
                        <input type="text" class="form-control" name="drill_water" value="{{$vessel->drill_water}}"/>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Upload PDF</label>
                        <input type="file" name="my_pdf">
                    </div>
                    <div class="form-group">
                        <label>Upload Image</label>
                        <input type="file" name="my_image">
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-lg btn-primary pull-right">Submit</button>
            <div class="clearfix"></div>
            <br>
        </form>

    </div>

@endsection

@section('footer')
    <script src="/js/angular.js"></script>

    <script>
        var myApp = angular.module('myApp', [], function($interpolateProvider) {
            $interpolateProvider.startSymbol('<%');
            $interpolateProvider.endSymbol('%>');
        });

        myApp.controller('editController', ['$scope', function($scope){

        }]);

    </script>
@endsection